name: ChangeSlots
version: ${project.version}
author: MrMicky
description: Light Bukkit and BungeeCord plugin to change the max players on your server without restart !
website: https://www.spigotmc.org/resources/changeslots.49648/
api-version: 1.13
main: fr.mrmicky.changeslots.ChangeSlotsBukkit
commands:
  setslots:
    description: Change the max players on the server
    usage: /<command> <slots>
    aliases: [setslot, changeslots]
