name: ChangeSlots
version: ${project.version}
author: MrMicky
description: A usefull plugin to change the max players on your server
website: https://www.spigotmc.org/resources/changeslots.49648/
main: fr.mrmicky.changeslots.ChangeSlotsBukkit
commands:
  setslots:
    description: Change the max players on the server
    usage: /<command> <slots>
    aliases: [setslot, changeslots]