Success: "&6The max players is now to &c%n."

NoArgument: "&cPlease indicate a number."

NoNumber: "&cPlease put a valid number."

Error: "&cAn error occurred, please check the console!"

NoPermission: "&cYou don't have access to that command!"

# If true, the server.properties (on Bukkit/Spigot) or the config.yml (on Bungee) will be update
# And the new slots will be keep after the restart
SaveOnRestart: false

# BungeeCord only: Does the plugin display real max players when you ping the server on server list?
UpdateServerPing: true
