Success: '&6The max slots is now to &c%n'

NoArgument: '&cPlease indicate a number'

NoNumber: '&cPlease put a valid number'

Error: '&cAn error occured, please check the console '

NoPermission: '&cYou don''t have access to that command'

#BungeeCord only: Does the plugin will display real max players when you ping the server on server list ?
UpdateServerPing: true